---
# vars file for postgresql

postgresql_host: "localhost"
postgresql_user: "postgres"

# log_directory value must be an absolute path
postgresql_config:
  - option: port
    value: 5432
  - option: log_destination
    value: syslog
  - option: log_directory
    value: /var/log/postgresql/
  
postgresql_authentication:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: md5}
  - {type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
  - {type: local, database: replication, user: all, auth_method: peer}
  - {type: host, database: replication, user: all, address: '0.0.0.0/0', auth_method: md5}
  - {type: host, database: replication, user: all, address: '::1/128', auth_method: md5}

postgresql_databases_users:
  - {database: maas_db, user: mass, userpassword: user1pass, priv: ALL}
