---
- hosts: "change_host"
  gather_facts: false
  become: yes
  tasks:
    - name: Set a hostname
      hostname:
        name: '{{ new_host }}'

    - name: Copy hosts file
      template:
        dest: /etc/hosts
        src: new_hosts.j2
        owner: root
        group: root
        mode: 0221


