all:
  children:
    dbservers
    maascontroller
    ldapservers
maascontroller:
  hosts:
    node1:
      ansible_host: 192.168.3.4
dbservers:
  hosts:
    neptune:
      ansible_host: 192.168.3.3
ldapservers:
  hosts:
    poseidon:
      ansible_host: 192.168.3.2
      ansible_user: ubuntu
