---
postgresql_version: 14
listen_addresses_host_ip: true
postgresql_host: "{{ ansible_ssh_host }}"
disable_socket_connecxion: false
create_users: false
create_databases: false
postgresql_config:
  - option: port
    value: "5432"
  - option: log_destination
    value: syslog
  - option: log_directory
    value: /var/log/postgresql/

