---
postgresql_version: 13
listen_addresses_host_ip: true
postgresql_host: "{{ ansible_ssh_host }}"
disable_socket_connecxion: false
create_users: true
create_databases: false
postgresql_config:
  - option: port
    value: "5432"
  - option: log_destination
    value: syslog
  - option: log_directory
    value: /var/log/postgresql/

postgresql_authentication:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: md5 }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '192.168.3.1/24', auth_method: md5 }
  - { type: host, database: all, user: all, address: '192.168.4.1/24', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  - { type: local, database: replication, user: all, auth_method: peer }
  - { type: host, database: replication, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: replication, user: all, address: '192.168.3.1/24', auth_method: md5 }
  - { type: host, database: replication, user: all, address: '192.168.4.1/24', auth_method: md5 }
  - { type: host, database: replication, user: all, address: '::1/128', auth_method: md5 }
